# Generated by Django 5.0.4 on 2024-04-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puntos_equipo',
            old_name='id_team',
            new_name='team',
        ),
    ]
