# Generated by Django 5.0.4 on 2024-04-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('futbol', '0005_alter_teams_fondo_alter_teams_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='nationality',
            field=models.CharField(max_length=100),
        ),
    ]
